# Site wide configuration

theme: jekyll-theme-cayman
title: Foster Forest
show_downloads: false
github:
  home:  https://timotheefouqueray.github.io/fosterforest/
  research: https://timotheefouqueray.github.io/fosterforest/recherche/recherche
  prospective: https://timotheefouqueray.github.io/fosterforest/prospective/prospective
  contact: https://timotheefouqueray.github.io/fosterforest/contact
  english: https://timotheefouqueray.github.io/fosterforest/english/home-eng






# logo: # filename of a logo image that has been placed into your images directory
# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Timothée Fouqueray
  # avatar: bio-photo.jpg
  github: timotheefouqueray 
  orcid: 0000-0003-4773-4733
 #  google:
   # plus: #username
    # analytics:
    # verify:
    # scholar: #id
